OnlinePharmacy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('account.urls')),
    path('product/', include('product.urls', namespace='product')),
    path('cart/', include('cart.urls')),
    path('order', include('order.urls')),
    # path('account/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('add/', views.add_product, name='add_product'),
    path('detail/', views.cart_detail, name='cart_detail'),
    path('delete_product/<pid>', views.delete_product, name='delete_product'),
    path('sub_product/<pid>', views.sub_product, name='sub_product'),
    path('plus_product/<pid>', views.plus_product, name='plus_product'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.post_list, name='product_list'),
    path('list/<tag_slug>/', views.post_list, name='product_list_by_tag'),
    path('<id>/<slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search_product, name='search_product'),
]

templates/base.html
<!DOCTYPE html>

<html>
    <head>
        {% load static %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

        <link href="{% static 'css/amazeui.css' %}" rel="stylesheet">
        <link href="{% static 'css/admin.css' %}" rel="stylesheet">
        <link href="{% static 'css/demo.css' %}" rel="stylesheet">

        {% block head %}{% endblock %}
    </head>

    <body>
        <div class="hmtop">
            <!--顶部导航条 -->
            <div class="am-container header">
                <!-- 登陆部分 -->
                <ul class="message-l">
                    <div class="topMessage">
                        <div class="menu-hd">
                            {% if request.user.is_authenticated %}
                                <a href="#" target="_top">欢迎您 {{ request.user.username }} ！</a>
                                <a href="{% url 'logout' %}" target="_top">登 出</a>
                            {% else %}
                                <a href="{% url 'login' %}" target="_top" class="h">亲，请登录</a>
                                <a href="{% url 'register' %}" target="_top">免费注册</a>
                            {% endif %}
                        </div>
                    </div>
                </ul>

                <ul class="message-r">
                    <div class="topMessage home">
                        <div class="menu-hd"><a href="{% url 'dashboard' %}" target="_top" class="h">商城首页</a></div>
                    </div>
                    <div class="topMessage my-shangcheng">
                        <div class="menu-hd MyShangcheng"><a href="#" target="_top"><i class="am-icon-user am-icon-fw"></i>个人中心</a></div>
                    </div>
                    <div class="topMessage mini-cart">
                        <div class="menu-hd"><a id="mc-menu-hd" href="{% url 'cart_detail' %}" target="_top"><i class="am-icon-shopping-cart  am-icon-fw"></i><span>购物车 </span><strong id="J_MiniCartNum" class="h"> {% if request.session.total_price %}¥{{request.session.total_price|floatformat:2}}{% endif %}</strong></a></div>
                    </div>
                </ul>
            </div>

            <!--悬浮搜索框-->

            <div class="nav white">
                <div class="logo"><img src="{% static 'img/logo.png' %}" /></div>
                <div class="logoBig">
                    <li><img src="{% static 'img/logobig.png' %}"/></li>
                </div>

                <div class="search-bar pr">
                    <a name="index_none_header_sysc" href="#"></a>
                    <form method="post" action="{% url 'product:search_product' %}">
                        {% csrf_token %}
                        <input id="searchInput" name="index_none_header_sysc" type="text" placeholder="药品名/症状/品牌" autocomplete="off">
                        <input id="ai-topsearch" class="submit am-btn" value="搜索" index="1" type="submit">
                    </form>
                </div>
            </div>


        </div>
        {% block body %}{% endblock %}
    </body>    
</html>